services:
  db:
    image: postgres:16
    container_name: product_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - product_network

  product_service:
    build: .
    container_name: product_service
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./migrations:/app/migrations    # <-- mount host migrations folder
    networks:
      - product_network



volumes:
  pgdata:

networks:
  product_network:
